config_version: 1

api:
  port: 8080

ping:
  interval_seconds: 10

  export:
    server:
      name: true
      address: true
      status: true
      motd: true
      players: true
      version: true
      updated_at: true